---
title: What Do People Look for in Someone to Date?
author: Gloria
date: '2019-09-04'
categories:
  - R
tags:
  - love science
slug: what-do-people-look-for-in-someone-to-date
showonlyimage: no
---
## Introduction

What is love? Love can be amazing, enjoyable, joyful; love can also be depressing, devastating, harmful. Undoubtedly, romantic relationships are complicated and perplexing. For years, researchers have spent effort attempting to figure out what makes people fall in love. People might have found their significant others in school, work, or other social situations. Speed dating is among one of the rising ways for people searching for a romantic relationship. When people make decisions on whether they would want to see a person again, their preferences indicate what they consider as important when picking a potentially long-term partner, and therefore analyzing choices of participants in speeding dating occasions is helpful in researching about long-term relationship. This project aims to explore and explain what attributes people are looking for in a date, and can provide some insights for companies working in the growing dating industry as well as individuals interested in this topic and those who are in search of romantic relationships. 

